; PlatformIO Project Configuration File
;
; THIS CONFIGURATION IS FOR THE ESP32-S3 N16R8 WITH THE OV5640 CAMERA
; THE BOARD USED TO BUILD THIS CODE WAS A CLONE.

[env:4d_systems_esp32s3_gen4_r8n16]
platform = espressif32
board = 4d_systems_esp32s3_gen4_r8n16
framework = arduino
monitor_speed = 115200

; Library dependency for the camera
lib_deps =
    esp32-camera
    adafruit/Adafruit Neopixel

# Disables DTR/RTS leaving the boot pins alone
monitor_dtr = 0
monitor_rts = 0

# OVERRIDE the board's hidden default
build_flags = 
    ; Force serial output back to COM port (UART0)
    -D ARDUINO_USB_CDC_ON_BOOT=0
    ; Enable PSRAM (Crucial for the camera)
    -D BOARD_HAS_PSRAM
    ; Set PSRAM mode to Octal for N16R8
    -D ARDUINO_RUNNING_CORE=1
    -D ARDUINO_EVENT_RUNNING_CORE=1